### PR TITLE
Upload playwright screenshots to aws and send link to PR

### PR DESCRIPTION
**Pull request by thiltunen**

### CODE REVIEW

**Comment by giosg-machine-user** [comment]
You can download updated screenshots [here](https:/design-system-dev-screenshots.s3.amazonaws.com/drone/7d27615a40d125e28a75a06d09c2ca515b7c3fe4/apps/storybook/tmp/current_screenshots.tar.gz)

**Comment by giosg-machine-user** [comment]
You can download updated screenshots [here](https:/design-system-dev-screenshots.s3.amazonaws.com/drone/483d9cd51c17f6bc31b39e0bef9cc2642f8c94db/current_screenshots.tar.gz)

**Comment by giosg-machine-user** [comment]
You can download screenshots here - https:/design-system-dev-screenshots.s3.amazonaws.com/drone/9dfa8c870353ff95ed9c8431e309ce95c6868351/playwright_screenshots.tar.gz)

**Comment by giosg-machine-user** [comment]
You can download screenshots here - https:/design-system-dev-screenshots.s3.amazonaws.com/drone/fc11cc4d7e8561dec7f8d6b7357341fdaa567d61/playwright_screenshots.tar.gz)

**Comment by giosg-machine-user** [comment]
You can download screenshots [here][https:/design-system-dev-screenshots.s3.amazonaws.com/drone/580c3ec3a1dc020c8e42d28f5cb3e896c5883f8f/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download screenshots [here](https:/design-system-dev-screenshots.s3.amazonaws.com/drone/93f88a172793a6796fddf8193350c4b89dbaed78/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download screenshots [here](https:/design-system-dev-screenshots.s3.amazonaws.com/drone/1536bb6f6e48f4b38c1992dda97cde10a96ee35f/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots here: https:/design-system-dev-screenshots.s3.amazonaws.com/drone/824960305824db13552e42d248ca1bf3c31748b6/playwright_screenshots.tar.gz

**Comment by thiltunen** [comment]
https://design-system-dev-screenshots.s3.amazonaws.com/drone/824960305824db13552e42d248ca1bf3c31748b6/playwright_screenshots.tar.gz

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/f57a8f51ebccf691495c3b7aecf778a1f25d038c/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/f42e62e2d355a71a327b5443e77ebe7b576633b3/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/77969df4ba2f295a1f4adb41efa06dedfd334126/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/48324e467d1acc21db2da45dd87fd652709b6365/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/0592826cf5dfe9e4f97b1ef71106a0f0123bf1ff/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/8d09e217439d454c0fa6f914325a8aa5f805275d/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/1e3681c3e7180156192a154980b336881bca35ee/playwright_screenshots.tar.gz).

**Comment by giosg-machine-user** [comment]
You can download playwright screenshots [here](https://design-system-dev-screenshots.s3.amazonaws.com/drone/d5a4a711635ba4a5556e31716609a512454f35e3/playwright_screenshots.tar.gz). If the "test-results" folder is empty, Playwright did not find any differences.

**Review by gab1991 — APPROVED** [review]

**Pull request merged**
